general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 10, y = 10 }
opacity = 0.9
decorations = "None"

[font]
normal = { family = "GeistMono Nerd Font", style = "Regular" }
bold = { family = "GeistMono Nerd Font", style = "Bold" }
italic = { family = "GeistMono Nerd Font", style = "Italic" }
size = 12.0
